os:
    - osx
    - linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -y libwxgtk3.0-dev libgtk2.0-dev; fi
    - git show -s --format="wxT(\"<a href=\\\"http://github.com/audacity/audacity/commit/%H\\\">%h</a> of %cd\")"
    - git show -s --format="wxT(\"<a href=\\\"http://github.com/audacity/audacity/commit/%H\\\">%h</a> of %cd\")" > ./src/RevisionIdent.h
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - FLAGS="-Wall -Wextra"
    - export CFLAGS="$CFLAGS $FLAGS"
    - export CXXFLAGS="$CXXFLAGS $FLAGS"
language:
    - cpp
script:
    - aclocal --install -I m4 && automake && ./configure && make
